language: node_js
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
    - eval "${MATRIX_EVAL}"
node_js:
  - "4"
  - "6"
compiler:
  - gcc
install:
  - npm install node-expat opencc
script:
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: precise
