language: node_js
node_js:
  - "4"
  - "6"
compiler:
  - gcc
env:
  - CXX=g++-4.8
install:
  - npm install node-expat opencc
script:
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: precise
