language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "4"
  - "6"
compiler:
  - gcc
install:
  - npm install node-expat opencc
script:
  - cp build.properties.travis build.properties
  - which node
  - ant test
branches:
  only:
    - master
    - development
sudo: required
dist: trusty
